### ISSUE TITLE
我应该如何安装呢？

### ISSUE THREAD

**Issue by MeowSalty** [jsp1256/qBittorrent_cross_complie#4]
下载luci-app-qbittorrent_1.0-1_all.ipk到路由器后执行
`opkg install /bt/luci-app-qbittorrent_1.0-1_all.ipk`
返回
```
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for qbittorrent-nox:
 *      libboost-system *       libboost-chrono *       libboost-random *       libQt5Core *   libQt5Network *  libQt5Xml *
 * opkg_install_cmd: Cannot install package qbittorrent-nox.
```
于是上--force-depends，返回
```
Installing luci-app-qbittorrent (1.0-1) to root...
Configuring luci-app-qbittorrent.
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-qbittorrent:
 *      qbittorrent-nox *
```
于是其他的依赖都没有被安装……这是要手动安装其他的依赖包吗……
| 路由器型号 	|            newifi d2           	|
|:----------:	|:------------------------------:	|
|    系统    	| PandoraBox 19.02 / LuCI Master 	|
|    芯片    	|            MT7621AT            	|

**Comment by hong0980** [comment]
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-qbittorrent:
 * 	qbittorrent-nox * 
 * opkg_install_cmd: Cannot install package luci-app-qbittorrent.
package/Makefile:65: recipe for target 'package/install' failed
make[2]: *** [package/install] Error 255
make[2]: Leaving directory '/home/hong/Openwrt/lede/lede'
package/Makefile:104: recipe for target '/home/hong/Openwrt/lede/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_install' failed
make[1]: *** [/home/hong/Openwrt/lede/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/hong/Openwrt/lede/lede'
/home/hong/Openwrt/lede/lede/include/toplevel.mk:216: recipe for target 'world' failed
make: *** [world] Error 2
编译出错，请问是什么问题。

**Comment by MeowSalty** [comment]
我觉得是因为缺乏qbittorrent-nox吧，因为这个包不在任何源当中。所以应该去手动安装所有的包。（因为太麻烦了所以目前已经放弃在路由器运行qb了，然后自己组了一台nas来运行。

> 收集的错误：
> 
> * satisfy_dependencies_for：无法满足luci-app-qbittorrent的以下依赖关系：
> * qbittorrent-nox *
> * opkg_install_cmd：无法安装软件包luci-app-qbittorrent。
>   package / Makefile：65：目标'package / install'的配方失败
>   make [2]：*** [package / install]错误255 
>   make [2]：离开目录'/ home / hong / Openwrt / lede / lede' 
>   包/ Makefile：104：目标的配方'/home/hong/Openwrt/lede/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_install'失败
>   make [1]：*** [/ home / hong / Openwrt / lede / lede / staging_dir / target-mipsel_24kc_musl / stamp / .package_install]错误2 
>   make [1]：离开目录'/ home / hong / Openwrt / lede / lede'/home/hong/Openwrt/lede/lede/include/ 
>   toplevel.mk ：216：目标'世界'的配方失败
>   make：*** [world]错误2 
>   编译出错，请问是什么问题。

**Comment by openwrt-1983** [comment]
上面的两位同学我已经编译固件成功了   有兴趣就加我qq 89 577 2799  咱们一块儿探讨吧

**Comment by openwrt-1983** [comment]
不会玩这个东西，不知道能不能艾特 @wsndshx @hong0980

**Comment by jsp1256** [comment]
@wsndshx 实际上这个是自行编译打包的，自然不会包含在任何源上，在ipk目录下应该有个qbittorrent-nox的ipk安装包，这是我强制写的依赖，你可以强制安装仅使用luci
@hong0980 同样的原因，没有把qbittorrent-nox编译进去，你可以修改Makefile文件去除这个依赖。
