### ISSUE TITLE
init.d下的qbittorrent脚本在4.1.6还有问题

### ISSUE THREAD

**Issue by hong0980** [jsp1256/qBittorrent_cross_complie#5]
init.d下的qbittorrent脚本在4.1.6还有问题，在lua下设置好下载路径，但在qBittorrent.conf中不正确。
![20190802213948](https://user-images.githubusercontent.com/32021831/62374664-03b98d00-b56f-11e9-9b22-fa33b16360f0.png)
![20190802214011](https://user-images.githubusercontent.com/32021831/62374678-0b793180-b56f-11e9-8685-b243ada742f6.png)
谢谢修复下。

**Comment by hong0980** [comment]
自己弄好了。是在`echo "Downloads\SavePath=$download_dir" >> $2/qBittorrent/config/qBittorrent.conf`这句download_dir也要改下。能不能在lua中加入日志和用户名及密码修改。谢谢！

**Comment by jsp1256** [comment]
请把修复的代码提交过来把，加入用户名和密码的修改前提得能生成这个密码的密文，如果支持的话可能会再加一层依赖，比如依赖个openssl-utils来生成密文
